version: "3.1"
services:
    src:
        image: php:8.0-apache
        ports: 
            - "80:80"
        volumes:
            - ./src:/var/src
        networks:
            - default
volumes:
    persistent:
