version: "3.1"
services:
    www:
        image: php:8.0-apache
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        networks:
            - default
volumes:
    persistent:
